image: Visual Studio 2017
build_script:
- ps: >-
    [xml]$doc = (Get-Content .\Library\SslLabsLib\SslLabsLib.csproj)

    $version = $doc.Project.PropertyGroup.VersionPrefix

    Update-AppveyorBuild -Version "$version.$env:APPVEYOR_BUILD_NUMBER"
- ps: # Core
- ps: dotnet restore
- ps: # Library
- ps: dotnet pack -c Release -o Nuget\ Library\SslLabsLib
- ps: # Tests
- ps: dotnet build -c Release Library\SslLabsLib.Tests
- ps: # Utilities
- ps: dotnet build -c Release Tools\SslLabsCli
- ps: dotnet build -c Release Tools\SslLabsMassScan
- ps: dotnet build -c Release Tools\TestApplication
test_script:
- ps: dotnet test -c Release Library\SslLabsLib.Tests
artifacts:
- path: Nuget\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: dgfUEGXULcqCTyNcS6UEDK8BCBi8y+M2+d4IFjnb3Gf9DqV34fMSp1XjxJg2AVRC
  on:
    branch: nuget